---
    ##########
    #
    # play to install epel, update yum packages and install docker on a centos box. Supports both centos6 and centos7
    #
-
  hosts: all
  gather_facts: yes
  sudo: yes
  tasks:
    - debug: "msg='Distribution {{ ansible_distribution_version }} {{ ansible_distribution }}'"
      name: " linux distibution"
    ##########
    #
    # Install epel
    #
    - name: install the epel rpm from a remote repo for centos6
      yum: name="{{ epel_rpm_centos6 }}" state=present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

    - name: install the epel rpm from a remote repo for centos7
      yum: name="{{ epel_rpm_centos7 }}" state=present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    ##########
    #
    # Upgrade all packages
    #
    - name: upgrade all packages
      yum: name=* state=latest

    ##########
    #
    # Install docker
    #
    - name: install docker-io for centos6
      yum: name="docker-io" state=present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

    - name: install docker for centos7
      yum: name="docker" state=present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    ##########
    #
    # Make sure it's enabled and started
    # chkconfig docker on
    # service docker start
    #
    - name: check if docker is running
      service: name=docker enabled=yes state=started

    ##########
    #
    # Other tools to install
    #
    - name: install your favorite tools
      yum: name="lynx" state=present
