---
    ##########
    #
    # play to install epel, update yum packages and install docker on a centos box. Supports both centos6 and centos7
    #
-
  hosts: all
  gather_facts: yes
  sudo: yes
  tasks:
    - debug: "msg='Distribution {{ ansible_distribution_version }} {{ ansible_distribution }}'"
      name: " linux distibution"
    ##########
    #
    # Install epel
    #
    - name: install the epel rpm from a remote repo for centos7
      yum: name="epel-release" state=present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    # ##########
    # #
    # # Upgrade all packages
    # #
    - name: upgrade all packages
      yum: name=* state=latest

    ##########
    #
    # Add docker repo
    #
    - name: Add docker repository
      yum_repository:
        name: dockerrepo
        description: Docker Repository
        baseurl: https://yum.dockerproject.org/repo/main/centos/7/
        enabled: yes
        gpgcheck: no

    ##########
    #
    # Install docker
    #
    - name: install docker for centos7
      yum: name="docker-engine" state=present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    ##########
    #
    # Make sure it's enabled and started
    # chkconfig docker on
    # service docker start
    #
    - name: check if docker is running
      service: name=docker enabled=yes state=started

    ##########
    #
    # Other tools to install
    #
    - name: install your favorite tools
      yum: name="lynx" state=present

    - name: install your favorite tools
      yum: name="jq" state=present
